<?xml version="1.0" encoding="UTF-8"?>
<WebServiceRequestEntity>
   <description></description>
   <name>Add Payment  - Cash</name>
   <tag></tag>
   <elementGuidId>2f34ca87-a092-4d96-b38d-cf14dcb63c78</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <connectionTimeout>-1</connectionTimeout>
   <followRedirects>false</followRedirects>
   <httpBody></httpBody>
   <httpBodyContent>{
  &quot;text&quot;: &quot;{\r\n  \&quot;Payment\&quot;: {\r\n    \&quot;id\&quot;: \&quot;payment_1\&quot;,\r\n    \&quot;Identifier\&quot;: {\r\n      \&quot;authority\&quot;: \&quot;Travelport\&quot;,\r\n      \&quot;value\&quot;: \&quot;A0656EFF-FAF4-456F-B061-0161008D6A6E\&quot;\r\n    },\r\n    \&quot;Amount\&quot;: {\r\n      \&quot;code\&quot;: \&quot;${currencyCode}\&quot;,  \r\n      \&quot;minorUnit\&quot;: 2, \r\n      \&quot;currencySource\&quot;: \&quot;Charged\&quot;, \r\n      \&quot;approximateInd\&quot;: true, \r\n      \&quot;value\&quot;: \&quot;${total_price_amount}\&quot;\r\n    },\r\n    \&quot;FormOfPaymentIdentifier\&quot;: {\r\n      \&quot;id\&quot;: \&quot;formOfPayment_4\&quot;,\r\n      \&quot;FormOfPaymentRef\&quot;: \&quot;formOfPayment_4\&quot;,\r\n      \&quot;Identifier\&quot;: {\r\n          \&quot;authority\&quot;: \&quot;Travelport\&quot;,\r\n          \&quot;value\&quot;: \&quot;A0656EFF-FAF4-456F-B061-0161008D6FOP\&quot;\r\n      }\r\n      \r\n    },\r\n    \&quot;OfferIdentifier\&quot;: [\r\n      {\r\n        \&quot;id\&quot;: \&quot;o0\&quot;,\r\n        \&quot;offerRef\&quot;: \&quot;o0\&quot;,\r\n        \&quot;Identifier\&quot;: {\r\n          \&quot;authority\&quot;: \&quot;${price_authority}\&quot;,\r\n          \&quot;value\&quot;: \&quot;${price_identfier_value}\&quot;\r\n        }\r\n      }\r\n    ]\r\n  }\r\n}&quot;,
  &quot;contentType&quot;: &quot;application/json&quot;,
  &quot;charset&quot;: &quot;UTF-8&quot;
}</httpBodyContent>
   <httpBodyType>text</httpBodyType>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>trackingId</name>
      <type>Main</type>
      <value>${guid}</value>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Authorization</name>
      <type>Main</type>
      <value>${token}</value>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Content-Type</name>
      <type>Main</type>
      <value>application/json</value>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>XAUTH_TRAVELPORT_ACCESSGROUP</name>
      <type>Main</type>
      <value>${XAUTH_TRAVELPORT_ACCESSGROUP_1G_XB7}</value>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Accept</name>
      <type>Main</type>
      <value>application/json</value>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Content-Version</name>
      <type>Main</type>
      <value>${version}</value>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name></name>
      <type>Main</type>
      <value></value>
   </httpHeaderProperties>
   <katalonVersion>8.0.5</katalonVersion>
   <maxResponseSize>-1</maxResponseSize>
   <migratedVersion>5.4.1</migratedVersion>
   <restRequestMethod>POST</restRequestMethod>
   <restUrl>${ts_environment}/${version}/air/paymentoffer/reservationworkbench/${reservationIdQf}/payments</restUrl>
   <serviceType>RESTful</serviceType>
   <soapBody></soapBody>
   <soapHeader></soapHeader>
   <soapRequestMethod></soapRequestMethod>
   <soapServiceEndpoint></soapServiceEndpoint>
   <soapServiceFunction></soapServiceFunction>
   <socketTimeout>-1</socketTimeout>
   <useServiceInfoFromWsdl>true</useServiceInfoFromWsdl>
   <variables>
      <defaultValue>GlobalVariable.ts_environment</defaultValue>
      <description></description>
      <id>d830ab38-91fb-48ad-96b9-352cd495ccaa</id>
      <masked>false</masked>
      <name>ts_environment</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.version</defaultValue>
      <description></description>
      <id>7aa2eeff-8086-4826-ae49-93e4d6a9f930</id>
      <masked>false</masked>
      <name>version</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.reservationIdQf</defaultValue>
      <description></description>
      <id>180fb8ef-8a2b-458a-8e0b-82e8d22db11b</id>
      <masked>false</masked>
      <name>reservationIdQf</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.guid</defaultValue>
      <description></description>
      <id>b2d2347b-f9a7-4b83-8e42-582c872329a6</id>
      <masked>false</masked>
      <name>guid</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.token</defaultValue>
      <description></description>
      <id>0b71ed91-2e1f-4862-b5c8-2a438e1cc5a3</id>
      <masked>false</masked>
      <name>token</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.XAUTH_TRAVELPORT_ACCESSGROUP_1G_XB7</defaultValue>
      <description></description>
      <id>cb778fc6-76e2-41b5-86ce-54b41a78b7ea</id>
      <masked>false</masked>
      <name>XAUTH_TRAVELPORT_ACCESSGROUP_1G_XB7</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.currencyCode</defaultValue>
      <description></description>
      <id>bfac2d08-29f5-4ac2-b1b7-771ff5960e4e</id>
      <masked>false</masked>
      <name>currencyCode</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.total_price_amount</defaultValue>
      <description></description>
      <id>9caefd42-15dd-4db3-ab41-e6844c2e855e</id>
      <masked>false</masked>
      <name>total_price_amount</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.price_authority</defaultValue>
      <description></description>
      <id>74314b4b-0d61-45af-a6ad-cfa14213590c</id>
      <masked>false</masked>
      <name>price_authority</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.price_identfier_value</defaultValue>
      <description></description>
      <id>42c3a6e3-5317-4999-b8cc-b3071cfac5ae</id>
      <masked>false</masked>
      <name>price_identfier_value</name>
   </variables>
   <wsdlAddress></wsdlAddress>
</WebServiceRequestEntity>
