<?xml version="1.0" encoding="UTF-8"?>
<WebServiceRequestEntity>
   <description></description>
   <name>Add Traveler</name>
   <tag></tag>
   <elementGuidId>9b42df8e-5765-4708-9dd5-79040712bdb2</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <connectionTimeout>-1</connectionTimeout>
   <followRedirects>false</followRedirects>
   <httpBody></httpBody>
   <httpBodyContent>{
  &quot;text&quot;: &quot;{\n  \&quot;Traveler\&quot; : {\n    \&quot;dob\&quot; : \&quot;1984-02-22\&quot;,\n    \&quot;gender\&quot; : \&quot;Male\&quot;,\n    \&quot;passengerTypeCode\&quot; : \&quot;ADT\&quot;,\n    \&quot;PersonName\&quot; : {\n      \&quot;@type\&quot; : \&quot;PersonNameDetail\&quot;,\n      \&quot;Prefix\&quot; : \&quot;Mr\&quot;,\n      \&quot;Given\&quot; : \&quot;JAMES\&quot;,\n      \&quot;Surname\&quot; : \&quot;HARKNESS\&quot;\n    },\n    \&quot;Telephone\&quot; : [ {\n      \&quot;@type\&quot; : \&quot;Telephone\&quot;,\n      \&quot;countryAccessCode\&quot; : \&quot;1\&quot;,\n      \&quot;areaCityCode\&quot; : \&quot;909\&quot;,\n      \&quot;phoneNumber\&quot; : \&quot;212456121\&quot;,\n      \&quot;extension\&quot; : \&quot;1243\&quot;,\n      \&quot;id\&quot; : \&quot;4\&quot;,\n      \&quot;cityCode\&quot; : \&quot;ORD\&quot;,\n      \&quot;role\&quot; : \&quot;Office\&quot;\n    },\n    {\n      \&quot;@type\&quot; : \&quot;Telephone\&quot;,\n      \&quot;countryAccessCode\&quot; : \&quot;1\&quot;,\n      \&quot;areaCityCode\&quot; : \&quot;303\&quot;,\n      \&quot;phoneNumber\&quot; : \&quot;111456121\&quot;,\n      \&quot;extension\&quot; : \&quot;1243\&quot;,\n      \&quot;id\&quot; : \&quot;4\&quot;,\n      \&quot;cityCode\&quot; : \&quot;ORD\&quot;,\n      \&quot;role\&quot; : \&quot;Office\&quot;\n    } ],\n    \&quot;Email\&quot; : [ {\n      \&quot;comment\&quot; : \&quot;Primary Email Id\&quot;,\n      \&quot;value\&quot; : \&quot;TravelerOne@gmail.com\&quot;\n    } ]\n  }\n}&quot;,
  &quot;contentType&quot;: &quot;application/json&quot;,
  &quot;charset&quot;: &quot;UTF-8&quot;
}</httpBodyContent>
   <httpBodyType>text</httpBodyType>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Accept</name>
      <type>Main</type>
      <value>application/json</value>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Content-Type</name>
      <type>Main</type>
      <value>application/json</value>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Authorization</name>
      <type>Main</type>
      <value>${token}</value>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>trackingId</name>
      <type>Main</type>
      <value>${guid}</value>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>XAUTH_TRAVELPORT_ACCESSGROUP</name>
      <type>Main</type>
      <value>${XAUTH_TRAVELPORT_ACCESSGROUP_1G_XB7}</value>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Accept-Version</name>
      <type>Main</type>
      <value>${version}</value>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Content-Version</name>
      <type>Main</type>
      <value>${version}</value>
   </httpHeaderProperties>
   <katalonVersion>8.0.5</katalonVersion>
   <maxResponseSize>-1</maxResponseSize>
   <migratedVersion>5.4.1</migratedVersion>
   <restRequestMethod>POST</restRequestMethod>
   <restUrl>${ts_environment}/${version}/air/book/traveler/reservationworkbench/${reservationIdQf}/travelers</restUrl>
   <serviceType>RESTful</serviceType>
   <soapBody></soapBody>
   <soapHeader></soapHeader>
   <soapRequestMethod></soapRequestMethod>
   <soapServiceEndpoint></soapServiceEndpoint>
   <soapServiceFunction></soapServiceFunction>
   <socketTimeout>-1</socketTimeout>
   <useServiceInfoFromWsdl>true</useServiceInfoFromWsdl>
   <variables>
      <defaultValue>GlobalVariable.ts_environment</defaultValue>
      <description></description>
      <id>f056d356-0e7b-45dc-afcc-e344fcd112c3</id>
      <masked>false</masked>
      <name>ts_environment</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.version</defaultValue>
      <description></description>
      <id>0aa58d99-3fd6-4d8e-a960-47ff5ada1dbb</id>
      <masked>false</masked>
      <name>version</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.reservationIdQf</defaultValue>
      <description></description>
      <id>8f9b5c6a-e4eb-425a-bea8-8d9e3c18bb0d</id>
      <masked>false</masked>
      <name>reservationIdQf</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.token</defaultValue>
      <description></description>
      <id>33e9331a-0fe3-4029-b476-da3f91af1346</id>
      <masked>false</masked>
      <name>token</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.guid</defaultValue>
      <description></description>
      <id>1fdce4f9-ed4b-483f-b7e7-1915524f93c3</id>
      <masked>false</masked>
      <name>guid</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.XAUTH_TRAVELPORT_ACCESSGROUP_1G_XB7</defaultValue>
      <description></description>
      <id>119c343d-3275-4644-a8b8-b3be1e490452</id>
      <masked>false</masked>
      <name>XAUTH_TRAVELPORT_ACCESSGROUP_1G_XB7</name>
   </variables>
   <wsdlAddress></wsdlAddress>
</WebServiceRequestEntity>
