<?xml version="1.0" encoding="UTF-8"?>
<WebServiceRequestEntity>
   <description></description>
   <name>Seat Book</name>
   <tag></tag>
   <elementGuidId>3ef4ffc1-441a-44bc-9165-65fb9f0cf716</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <connectionTimeout>-1</connectionTimeout>
   <followRedirects>false</followRedirects>
   <httpBody></httpBody>
   <httpBodyContent>{
  &quot;text&quot;: &quot;{\n    \&quot;OfferQueryBuildAncillaryOffersFromCatalogOfferings\&quot;: {\n        \&quot;BuildAncillaryOffersFromCatalogOfferings\&quot;: [\n            {\n                \&quot;@type\&quot;: \&quot;BuildAncillaryOffersFromCatalogOfferingsAirSeat\&quot;,\n                \&quot;CatalogOfferingsIdentifier\&quot;: {\n                    \&quot;Identifier\&quot;: {\n                        \&quot;value\&quot;: \&quot;${catalogOfferingsIdentifierValue}\&quot;\n                    }\n                },\n                \&quot;TravelerIdentifier\&quot;: {\n                    \&quot;Identifier\&quot;: {\n                        \&quot;value\&quot;: \&quot;${termsAndConditionsIdentifierValue}\&quot;\n                    }\n                },\n                \&quot;SeatAssignment\&quot;: \&quot;${firstSeatAvailablilityValue}\&quot;\n            }\n        ]\n    }\n}&quot;,
  &quot;contentType&quot;: &quot;text/plain&quot;,
  &quot;charset&quot;: &quot;UTF-8&quot;
}</httpBodyContent>
   <httpBodyType>text</httpBodyType>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>XAUTH_TRAVELPORT_ACCESSGROUP</name>
      <type>Main</type>
      <value>${XAUTH_TRAVELPORT_ACCESSGROUP_1G_XB7}</value>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Authorization</name>
      <type>Main</type>
      <value>${token}</value>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>E2EtrackingId</name>
      <type>Main</type>
      <value>${guid}</value>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Accept</name>
      <type>Main</type>
      <value>application/json</value>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Content-Version</name>
      <type>Main</type>
      <value>${version}</value>
   </httpHeaderProperties>
   <katalonVersion>8.0.5</katalonVersion>
   <maxResponseSize>-1</maxResponseSize>
   <migratedVersion>5.4.1</migratedVersion>
   <restRequestMethod>POST</restRequestMethod>
   <restUrl>${ts_environment}/${version}/air/book/ancillary/reservations//${reservationIdQf}/offers/${offerIdQf}</restUrl>
   <serviceType>RESTful</serviceType>
   <soapBody></soapBody>
   <soapHeader></soapHeader>
   <soapRequestMethod></soapRequestMethod>
   <soapServiceEndpoint></soapServiceEndpoint>
   <soapServiceFunction></soapServiceFunction>
   <socketTimeout>-1</socketTimeout>
   <useServiceInfoFromWsdl>true</useServiceInfoFromWsdl>
   <variables>
      <defaultValue>GlobalVariable.ts_environment</defaultValue>
      <description></description>
      <id>4de70b19-355b-495b-984a-3ec7e9608ce1</id>
      <masked>false</masked>
      <name>ts_environment</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.version</defaultValue>
      <description></description>
      <id>ca263a04-7afb-413a-8e86-a8f2e443034f</id>
      <masked>false</masked>
      <name>version</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.reservationIdQf</defaultValue>
      <description></description>
      <id>53b4aba5-8519-4670-a51e-7b4b348360c9</id>
      <masked>false</masked>
      <name>reservationIdQf</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.offerIdQf</defaultValue>
      <description></description>
      <id>9cd0de9d-082e-4a86-8d7b-c8486b234ab6</id>
      <masked>false</masked>
      <name>offerIdQf</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.XAUTH_TRAVELPORT_ACCESSGROUP_1G_XB7</defaultValue>
      <description></description>
      <id>569f8473-4512-441d-9179-c532fdaf99f5</id>
      <masked>false</masked>
      <name>XAUTH_TRAVELPORT_ACCESSGROUP_1G_XB7</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.token</defaultValue>
      <description></description>
      <id>4d3deaa9-052f-4089-8527-32d8aab4f600</id>
      <masked>false</masked>
      <name>token</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.guid</defaultValue>
      <description></description>
      <id>59bcdb7d-d23d-4655-a7c0-b4e431e8942f</id>
      <masked>false</masked>
      <name>guid</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.catalogOfferingsIdentifierValue</defaultValue>
      <description></description>
      <id>380a5103-5d53-4393-8743-f3b74fdc83a0</id>
      <masked>false</masked>
      <name>catalogOfferingsIdentifierValue</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.termsAndConditionsIdentifierValue</defaultValue>
      <description></description>
      <id>daf38d1d-241e-4e7c-be4d-1cedcc69c5f0</id>
      <masked>false</masked>
      <name>termsAndConditionsIdentifierValue</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.firstSeatAvailablilityValue</defaultValue>
      <description></description>
      <id>4f1e647d-c60e-4f66-95d3-c01500a170e0</id>
      <masked>false</masked>
      <name>firstSeatAvailablilityValue</name>
   </variables>
   <wsdlAddress></wsdlAddress>
</WebServiceRequestEntity>
