<?xml version="1.0" encoding="UTF-8"?>
<WebServiceRequestEntity>
   <description></description>
   <name>Add Payment - Credit</name>
   <tag></tag>
   <elementGuidId>96b4c293-a73d-4096-8aad-0a2a7086feaa</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <connectionTimeout>-1</connectionTimeout>
   <followRedirects>false</followRedirects>
   <httpBody></httpBody>
   <httpBodyContent>{
  &quot;text&quot;: &quot;{\r\n  \&quot;Payment\&quot;: {\r\n    \&quot;id\&quot;: \&quot;paymentCard_4\&quot;,\r\n    \&quot;Identifier\&quot;: {\r\n      \&quot;authority\&quot;: \&quot;Travelport\&quot;,\r\n      \&quot;value\&quot;: \&quot;A0656EFF-FAF4-456F-B061-0161008D6A6E\&quot;\r\n    },\r\n    \&quot;Amount\&quot;: {\r\n      \&quot;code\&quot;: \&quot;${currencyCode}\&quot;,  \r\n      \&quot;minorUnit\&quot;: 2, \r\n      \&quot;currencySource\&quot;: \&quot;Charged\&quot;, \r\n      \&quot;approximateInd\&quot;: true, \r\n      \&quot;value\&quot;: \&quot;${total_price_amount}\&quot;\r\n    },\r\n    \&quot;FormOfPaymentIdentifier\&quot;: {\r\n      \&quot;id\&quot;: \&quot;formOfPayment_5\&quot;,\r\n      \&quot;FormOfPaymentRef\&quot;: \&quot;formOfPayment_5\&quot;,\r\n      \&quot;Identifier\&quot;: {\r\n          \&quot;authority\&quot;: \&quot;Travelport\&quot;,\r\n          \&quot;value\&quot;: \&quot;A0656EFF-FAF4-456F-B061-0161008D6FOP\&quot;\r\n      }\r\n      \r\n    },\r\n    \&quot;OfferIdentifier\&quot;: [\r\n      {\r\n        \&quot;id\&quot;: \&quot;${offerId}\&quot;,\r\n        \&quot;offerRef\&quot;: \&quot;${offerId}\&quot;,\r\n        \&quot;Identifier\&quot;: {\r\n          \&quot;authority\&quot;: \&quot;SQ\&quot;,\r\n          \&quot;value\&quot;: \&quot;${offerIdentifier}\&quot;\r\n        }\r\n      }\r\n    ]\r\n  }\r\n}&quot;,
  &quot;contentType&quot;: &quot;application/json&quot;,
  &quot;charset&quot;: &quot;UTF-8&quot;
}</httpBodyContent>
   <httpBodyType>text</httpBodyType>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Accept</name>
      <type>Main</type>
      <value>application/json</value>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Content-Type</name>
      <type>Main</type>
      <value>application/json</value>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Content-Version</name>
      <type>Main</type>
      <value>${version}</value>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Authorization</name>
      <type>Main</type>
      <value>${token}</value>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>trackingId</name>
      <type>Main</type>
      <value>${guid}</value>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>XAUTH_TRAVELPORT_ACCESSGROUP</name>
      <type>Main</type>
      <value>${XAUTH_TRAVELPORT_ACCESSGROUP_1G_69Z9}</value>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Accept-Version</name>
      <type>Main</type>
      <value>6</value>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>OAUTH_RESOURCEOWNERINFO</name>
      <type>Main</type>
      <value>${XAUTH_TRAVELPORT_ACCESSGROUP_1G_79JP}</value>
   </httpHeaderProperties>
   <katalonVersion>8.0.5</katalonVersion>
   <maxResponseSize>-1</maxResponseSize>
   <migratedVersion>5.4.1</migratedVersion>
   <restRequestMethod>POST</restRequestMethod>
   <restUrl>${ts_environment}/${version}/air/paymentoffer/reservationworkbench/${reservationIdSq}/payments</restUrl>
   <serviceType>RESTful</serviceType>
   <soapBody></soapBody>
   <soapHeader></soapHeader>
   <soapRequestMethod></soapRequestMethod>
   <soapServiceEndpoint></soapServiceEndpoint>
   <soapServiceFunction></soapServiceFunction>
   <socketTimeout>-1</socketTimeout>
   <useServiceInfoFromWsdl>true</useServiceInfoFromWsdl>
   <variables>
      <defaultValue>GlobalVariable.ts_environment</defaultValue>
      <description></description>
      <id>93d41582-8598-4ee1-8a3d-6c004bc7e5c9</id>
      <masked>false</masked>
      <name>ts_environment</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.version</defaultValue>
      <description></description>
      <id>f13271c2-5748-422c-a70d-b14cdf152af4</id>
      <masked>false</masked>
      <name>version</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.reservationIdSq</defaultValue>
      <description></description>
      <id>d3c9bd5b-7a75-492f-8aeb-b99c71882dcc</id>
      <masked>false</masked>
      <name>reservationIdSq</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.token</defaultValue>
      <description></description>
      <id>f78ee001-3abf-4f1d-bd09-bf43e6abd36a</id>
      <masked>false</masked>
      <name>token</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.guid</defaultValue>
      <description></description>
      <id>a4f92b0d-60d3-4f08-b074-2150f1c70c6d</id>
      <masked>false</masked>
      <name>guid</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.XAUTH_TRAVELPORT_ACCESSGROUP_1G_69Z9</defaultValue>
      <description></description>
      <id>675958c4-15c3-4b3b-a4f2-4df2efc89717</id>
      <masked>false</masked>
      <name>XAUTH_TRAVELPORT_ACCESSGROUP_1G_69Z9</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.XAUTH_TRAVELPORT_ACCESSGROUP_1G_79JP</defaultValue>
      <description></description>
      <id>5574861b-671d-4955-a2b8-740b3ee8e313</id>
      <masked>false</masked>
      <name>XAUTH_TRAVELPORT_ACCESSGROUP_1G_79JP</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.currencyCode</defaultValue>
      <description></description>
      <id>3648a916-0058-4e8e-b8fd-457963923efe</id>
      <masked>false</masked>
      <name>currencyCode</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.total_price_amount</defaultValue>
      <description></description>
      <id>e3fed01c-724f-47cf-bd05-2322214fb446</id>
      <masked>false</masked>
      <name>total_price_amount</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.offerId</defaultValue>
      <description></description>
      <id>8f36ae1f-2ec2-4ecb-a718-56367a45ff6c</id>
      <masked>false</masked>
      <name>offerId</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.offerIdentifier</defaultValue>
      <description></description>
      <id>12838024-b437-4756-b081-a1d2d99de81d</id>
      <masked>false</masked>
      <name>offerIdentifier</name>
   </variables>
   <wsdlAddress></wsdlAddress>
</WebServiceRequestEntity>
