<?xml version="1.0" encoding="UTF-8"?>
<WebServiceRequestEntity>
   <description></description>
   <name>Search Request - SQ (1)</name>
   <tag></tag>
   <elementGuidId>500b85d5-09f7-4a52-ba91-45ca676cdebc</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <connectionTimeout>-1</connectionTimeout>
   <followRedirects>false</followRedirects>
   <httpBody></httpBody>
   <httpBodyContent>{
  &quot;text&quot;: &quot;{\n\t\&quot;CatalogOfferingsQueryRequest\&quot;: {\n\t\t\&quot;CatalogOfferingsRequest\&quot;: [\n\t\t\t{\n\t\t\t\t\&quot;@type\&quot;: \&quot;CatalogOfferingsRequestAir\&quot;,\n\t\t\t\t\&quot;maxNumberOfOffersToReturn\&quot;: 50,\n\t\t\t\t\&quot;offersPerPage\&quot;: 20,\n\t\t\t\t\&quot;contentSourceList\&quot;: [\n\t\t\t\t\t\&quot;NDC\&quot;\n\t\t\t\t],\n\t\t\t\t\&quot;PassengerCriteria\&quot;: [\n\t\t\t\t\t{\n\t\t\t\t\t\t\&quot;number\&quot;: 1,\n\t\t\t\t\t\t\&quot;passengerTypeCode\&quot;: \&quot;ADT\&quot;\n\t\t\t\t\t},\n\t\t\t\t\t{\n\t\t\t\t\t\t\&quot;number\&quot;: 1,\n\t\t\t\t\t\t\&quot;passengerTypeCode\&quot;: \&quot;CHD\&quot;\n\t\t\t\t\t}\n\t\t\t\t],\n\t\t\t\t\&quot;SearchCriteriaFlight\&quot;: [\n\t\t\t\t\t{\n\t\t\t\t\t\t\&quot;departureDate\&quot;: \&quot;${InitialDeparture}\&quot;,\n\t\t\t\t\t\t\&quot;From\&quot;: {\n\t\t\t\t\t\t\t\&quot;value\&quot;: \&quot;SIN\&quot;\n\t\t\t\t\t\t},\n\t\t\t\t\t\t\&quot;To\&quot;: {\n\t\t\t\t\t\t\t\&quot;value\&quot;: \&quot;MEL\&quot;\n\t\t\t\t\t\t}\n\t\t\t\t\t}\n\t\t\t\t],\n\t\t\t\t\&quot;SearchModifiersAir\&quot;: {\n\t\t\t\t\t\&quot;CarrierPreference\&quot;: [\n\t\t\t\t\t\t{\n\t\t\t\t\t\t\t\&quot;type\&quot;: \&quot;Permitted\&quot;,\n\t\t\t\t\t\t\t\&quot;carriers\&quot;: [\n\t\t\t\t\t\t\t\t\&quot;SQ\&quot;\n\t\t\t\t\t\t\t]\n\t\t\t\t\t\t}\n\t\t\t\t\t],\n                    \&quot;CabinPreference\&quot;: [\n\t\t\t\t\t\t{\n\t\t\t\t\t\t\t\&quot;type\&quot;: \&quot;Permitted\&quot;,\n\t\t\t\t\t\t\t\&quot;cabins\&quot;: [\n\t\t\t\t\t\t\t\t\&quot;Business\&quot;\n\t\t\t\t\t\t\t]\n\t\t\t\t\t\t}\n\t\t\t\t\t]\n\t\t\t\t}\n\t\t\t}\n\t\t]\n\t}\n}&quot;,
  &quot;contentType&quot;: &quot;application/json&quot;,
  &quot;charset&quot;: &quot;UTF-8&quot;
}</httpBodyContent>
   <httpBodyType>text</httpBodyType>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Accept</name>
      <type>Main</type>
      <value>application/json</value>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Content-Type</name>
      <type>Main</type>
      <value>application/json</value>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Authorization</name>
      <type>Main</type>
      <value>${token}</value>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>E2ETrackingID</name>
      <type>Main</type>
      <value>${guid}</value>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>XAUTH_TRAVELPORT_ACCESSGROUP</name>
      <type>Main</type>
      <value>${XAUTH_TRAVELPORT_ACCESSGROUP_1G_69Z9}</value>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Accept-Version</name>
      <type>Main</type>
      <value>${version}</value>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Content-Version</name>
      <type>Main</type>
      <value>${version}</value>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ReservationResource_Identifier</name>
      <type>Main</type>
      <value>${eCacheIdSqMod}</value>
   </httpHeaderProperties>
   <katalonVersion>8.0.5</katalonVersion>
   <maxResponseSize>-1</maxResponseSize>
   <migratedVersion>5.4.1</migratedVersion>
   <restRequestMethod>POST</restRequestMethod>
   <restUrl>${ts_environment}/${version}/air/search/catalogofferings?view=detail</restUrl>
   <serviceType>RESTful</serviceType>
   <soapBody></soapBody>
   <soapHeader></soapHeader>
   <soapRequestMethod></soapRequestMethod>
   <soapServiceEndpoint></soapServiceEndpoint>
   <soapServiceFunction></soapServiceFunction>
   <socketTimeout>-1</socketTimeout>
   <useServiceInfoFromWsdl>true</useServiceInfoFromWsdl>
   <variables>
      <defaultValue>GlobalVariable.ts_environment</defaultValue>
      <description></description>
      <id>9aa4ba4a-0a9b-482d-97a8-360c128d7124</id>
      <masked>false</masked>
      <name>ts_environment</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.version</defaultValue>
      <description></description>
      <id>1810c22c-7cbb-4216-9d7b-9073c6290a6f</id>
      <masked>false</masked>
      <name>version</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.token</defaultValue>
      <description></description>
      <id>d733ba69-806b-423f-b3fe-a65f34ec02bc</id>
      <masked>false</masked>
      <name>token</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.guid</defaultValue>
      <description></description>
      <id>75a4b2e4-76df-4f1e-a274-ab011a00caed</id>
      <masked>false</masked>
      <name>guid</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.XAUTH_TRAVELPORT_ACCESSGROUP_1G_69Z9</defaultValue>
      <description></description>
      <id>d9fb694a-371c-439f-a96c-6164e5950d84</id>
      <masked>false</masked>
      <name>XAUTH_TRAVELPORT_ACCESSGROUP_1G_69Z9</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.eCacheIdSqMod</defaultValue>
      <description></description>
      <id>ad8b31e2-ffdc-45e0-97ba-0a6684e95196</id>
      <masked>false</masked>
      <name>eCacheIdSqMod</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.InitialDeparture</defaultValue>
      <description></description>
      <id>912713e3-ed82-4b5d-839a-49574c257858</id>
      <masked>false</masked>
      <name>InitialDeparture</name>
   </variables>
   <wsdlAddress></wsdlAddress>
</WebServiceRequestEntity>
