<?xml version="1.0" encoding="UTF-8"?>
<WebServiceRequestEntity>
   <description></description>
   <name>Add Payment - Credit</name>
   <tag></tag>
   <elementGuidId>d66c9b7b-6a0f-42b2-a5fa-bc191995fe80</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <connectionTimeout>-1</connectionTimeout>
   <followRedirects>false</followRedirects>
   <httpBody></httpBody>
   <httpBodyContent>{
  &quot;text&quot;: &quot;{\r\n  \&quot;Payment\&quot;: {\r\n    \&quot;id\&quot;: \&quot;paymentCard_4\&quot;,\r\n    \&quot;Identifier\&quot;: {\r\n      \&quot;authority\&quot;: \&quot;Travelport\&quot;,\r\n      \&quot;value\&quot;: \&quot;A0656EFF-FAF4-456F-B061-0161008D6A6E\&quot;\r\n    },\r\n    \&quot;Amount\&quot;: {\r\n      \&quot;code\&quot;: \&quot;${currencyCode}\&quot;,  \r\n      \&quot;minorUnit\&quot;: 2, \r\n      \&quot;currencySource\&quot;: \&quot;Charged\&quot;, \r\n      \&quot;approximateInd\&quot;: true, \r\n      \&quot;value\&quot;: \&quot;${total_price_amount}\&quot;\r\n    },\r\n    \&quot;FormOfPaymentIdentifier\&quot;: {\r\n      \&quot;id\&quot;: \&quot;formOfPayment_5\&quot;,\r\n      \&quot;FormOfPaymentRef\&quot;: \&quot;formOfPayment_5\&quot;,\r\n      \&quot;Identifier\&quot;: {\r\n          \&quot;authority\&quot;: \&quot;Travelport\&quot;,\r\n          \&quot;value\&quot;: \&quot;A0656EFF-FAF4-456F-B061-0161008D6FOP\&quot;\r\n      }\r\n      \r\n    },\r\n    \&quot;OfferIdentifier\&quot;: [\r\n      {\r\n        \&quot;id\&quot;: \&quot;${offerId}\&quot;,\r\n        \&quot;offerRef\&quot;: \&quot;${offerId}\&quot;,\r\n        \&quot;Identifier\&quot;: {\r\n          \&quot;authority\&quot;: \&quot;SQ\&quot;,\r\n          \&quot;value\&quot;: \&quot;${offerIdentifier}\&quot;\r\n        }\r\n      }\r\n    ]\r\n  }\r\n}&quot;,
  &quot;contentType&quot;: &quot;application/json&quot;,
  &quot;charset&quot;: &quot;UTF-8&quot;
}</httpBodyContent>
   <httpBodyType>text</httpBodyType>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Accept</name>
      <type>Main</type>
      <value>application/json</value>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Content-Type</name>
      <type>Main</type>
      <value>application/json</value>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Content-Version</name>
      <type>Main</type>
      <value>${version}</value>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Authorization</name>
      <type>Main</type>
      <value>${token}</value>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>trackingId</name>
      <type>Main</type>
      <value>${guid}</value>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>XAUTH_TRAVELPORT_ACCESSGROUP</name>
      <type>Main</type>
      <value>${XAUTH_TRAVELPORT_ACCESSGROUP_1G_69Z9}</value>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Accept-Version</name>
      <type>Main</type>
      <value>6</value>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>OAUTH_RESOURCEOWNERINFO</name>
      <type>Main</type>
      <value>${XAUTH_TRAVELPORT_ACCESSGROUP_1G_79JP}</value>
   </httpHeaderProperties>
   <katalonVersion>8.0.5</katalonVersion>
   <maxResponseSize>-1</maxResponseSize>
   <migratedVersion>5.4.1</migratedVersion>
   <restRequestMethod>POST</restRequestMethod>
   <restUrl>${ts_environment}/${version}/air/paymentoffer/reservationworkbench/${reservationIdSq}/payments</restUrl>
   <serviceType>RESTful</serviceType>
   <soapBody></soapBody>
   <soapHeader></soapHeader>
   <soapRequestMethod></soapRequestMethod>
   <soapServiceEndpoint></soapServiceEndpoint>
   <soapServiceFunction></soapServiceFunction>
   <socketTimeout>-1</socketTimeout>
   <useServiceInfoFromWsdl>true</useServiceInfoFromWsdl>
   <variables>
      <defaultValue>GlobalVariable.ts_environment</defaultValue>
      <description></description>
      <id>472c94af-1627-407f-8ef8-e2515d37cefd</id>
      <masked>false</masked>
      <name>ts_environment</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.version</defaultValue>
      <description></description>
      <id>a225d549-8719-41b9-8679-f49093390411</id>
      <masked>false</masked>
      <name>version</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.reservationIdSq</defaultValue>
      <description></description>
      <id>3553ce2e-9a1f-423b-b917-f50d303dee82</id>
      <masked>false</masked>
      <name>reservationIdSq</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.token</defaultValue>
      <description></description>
      <id>298ab431-7069-460d-8fe5-1f08bec3764a</id>
      <masked>false</masked>
      <name>token</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.guid</defaultValue>
      <description></description>
      <id>864b54f8-7104-4c4c-81ee-7a48444ad44c</id>
      <masked>false</masked>
      <name>guid</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.XAUTH_TRAVELPORT_ACCESSGROUP_1G_69Z9</defaultValue>
      <description></description>
      <id>f7e99aa0-6d46-4dbb-9ae8-02260b096bad</id>
      <masked>false</masked>
      <name>XAUTH_TRAVELPORT_ACCESSGROUP_1G_69Z9</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.XAUTH_TRAVELPORT_ACCESSGROUP_1G_79JP</defaultValue>
      <description></description>
      <id>2ad52493-5a86-45cb-9552-c9249599e845</id>
      <masked>false</masked>
      <name>XAUTH_TRAVELPORT_ACCESSGROUP_1G_79JP</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.currencyCode</defaultValue>
      <description></description>
      <id>86c4754c-90b4-4dfc-810c-3913bcb9c9d5</id>
      <masked>false</masked>
      <name>currencyCode</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.total_price_amount</defaultValue>
      <description></description>
      <id>6608fed3-9cc9-4d8b-889c-4fe7647e76a9</id>
      <masked>false</masked>
      <name>total_price_amount</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.offerId</defaultValue>
      <description></description>
      <id>90ae587d-5e6c-4b18-91cc-7f30a99f91f5</id>
      <masked>false</masked>
      <name>offerId</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.offerIdentifier</defaultValue>
      <description></description>
      <id>ac7848be-3f9c-4314-9808-a0b132040150</id>
      <masked>false</masked>
      <name>offerIdentifier</name>
   </variables>
   <wsdlAddress></wsdlAddress>
</WebServiceRequestEntity>
