<?xml version="1.0" encoding="UTF-8"?>
<WebServiceRequestEntity>
   <description></description>
   <name>Price Request FullPayload Path GDS</name>
   <tag></tag>
   <elementGuidId>27cfa02b-84ed-4eba-9dda-d1fb8c043bd3</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <connectionTimeout>-1</connectionTimeout>
   <followRedirects>false</followRedirects>
   <httpBody></httpBody>
   <httpBodyContent>{
  &quot;text&quot;: &quot;{\r\n  \&quot;OfferQueryBuildFromProducts\&quot;: {\r\n    \&quot;lowFareFinderInd\&quot;: true,\r\n    \&quot;returnBrandedFaresInd\&quot;: true,\r\n    \&quot;BuildFromProductsRequest\&quot;: {\r\n      \&quot;@type\&quot;: \&quot;BuildFromProductsRequestAir\&quot;,\r\n      \&quot;PricingModifiersAir\&quot;: {\r\n        \&quot;@type\&quot;: \&quot;PricingModifiersAir\&quot;,\r\n        \&quot;currencyCode\&quot;: \&quot;AUD\&quot;,\r\n        \&quot;FareSelection\&quot;: {\r\n          \&quot;@type\&quot;: \&quot;FareSelectionDetail\&quot;,\r\n          \&quot;fareType\&quot;: \&quot;PublicFaresOnly\&quot;\r\n        }\r\n      },\r\n      \&quot;PassengerCriteria\&quot;: [\r\n        {\r\n          \&quot;@type\&quot;: \&quot;PassengerCriteria\&quot;,\r\n          \&quot;number\&quot;: 1,\r\n          \&quot;passengerTypeCode\&quot;: \&quot;ADT\&quot;\r\n        }\r\n      ],\r\n      \&quot;ProductCriteriaAir\&quot;: [\r\n        {\r\n          \&quot;sequence\&quot;: 1,\r\n          \&quot;SpecificFlightCriteria\&quot;: [\r\n            {\r\n              \&quot;carrier\&quot;: \&quot;SQ\&quot;,\r\n              \&quot;flightNumber\&quot;: \&quot;424\&quot;,\r\n              \&quot;departureDate\&quot;: \&quot;2021-12-16\&quot;,\r\n              \&quot;departureTime\&quot;: \&quot;18:45:00\&quot;,\r\n              \&quot;arrivalDate\&quot;: \&quot;2021-12-16\&quot;,\r\n              \&quot;arrivalTime\&quot;: \&quot;22:10:00\&quot;,\r\n              \&quot;from\&quot;: \&quot;SIN\&quot;,\r\n              \&quot;to\&quot;: \&quot;BOM\&quot;,\r\n              \&quot;cabin\&quot;: \&quot;Economy\&quot;,\r\n              \&quot;classOfService\&quot;: \&quot;B\&quot;,\r\n              \&quot;segmentSequence\&quot;: 1\r\n            }\r\n          ]\r\n        },\r\n        {\r\n          \&quot;sequence\&quot;: 2,\r\n          \&quot;SpecificFlightCriteria\&quot;: [\r\n            {\r\n              \&quot;carrier\&quot;: \&quot;SQ\&quot;,\r\n              \&quot;flightNumber\&quot;: \&quot;423\&quot;,\r\n              \&quot;departureDate\&quot;: \&quot;2021-12-21\&quot;,\r\n              \&quot;departureTime\&quot;: \&quot;23:35:00\&quot;,\r\n              \&quot;arrivalDate\&quot;: \&quot;2021-12-22\&quot;,\r\n              \&quot;arrivalTime\&quot;: \&quot;07:30:00\&quot;,\r\n              \&quot;from\&quot;: \&quot;BOM\&quot;,\r\n              \&quot;to\&quot;: \&quot;SIN\&quot;,\r\n              \&quot;cabin\&quot;: \&quot;Economy\&quot;,\r\n              \&quot;classOfService\&quot;: \&quot;B\&quot;,\r\n              \&quot;segmentSequence\&quot;: 1\r\n            }\r\n          ]\r\n        }\r\n      ]\r\n    },\r\n    \&quot;FareRuleType\&quot;: \&quot;ShortText\&quot;,\r\n    \&quot;FareRuleCategory\&quot;: [\r\n      \&quot;Stopovers\&quot;\r\n    ]\r\n  }\r\n}&quot;,
  &quot;contentType&quot;: &quot;application/json&quot;,
  &quot;charset&quot;: &quot;UTF-8&quot;
}</httpBodyContent>
   <httpBodyType>text</httpBodyType>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Accept</name>
      <type>Main</type>
      <value>application/json</value>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Content-Type</name>
      <type>Main</type>
      <value>application/json</value>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>E2ETrackingID</name>
      <type>Main</type>
      <value>${$guid}</value>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Identity-Key</name>
      <type>Main</type>
      <value>${Identity-Key}</value>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>XAUTH_TRAVELPORT_ACCESSGROUP</name>
      <type>Main</type>
      <value>${XAUTH_TRAVELPORT_ACCESSGROUP_1G}</value>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Accept-Version</name>
      <type>Main</type>
      <value>${Version}</value>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Content-Version</name>
      <type>Main</type>
      <value>${Version}</value>
   </httpHeaderProperties>
   <katalonVersion>8.1.0</katalonVersion>
   <maxResponseSize>-1</maxResponseSize>
   <migratedVersion>5.4.1</migratedVersion>
   <restRequestMethod>POST</restRequestMethod>
   <restUrl>https://api.apim-a.zu2.qa.travelport.io:443/uat/${Version}/air/price/offers/buildfromproducts</restUrl>
   <serviceType>RESTful</serviceType>
   <soapBody></soapBody>
   <soapHeader></soapHeader>
   <soapRequestMethod></soapRequestMethod>
   <soapServiceEndpoint></soapServiceEndpoint>
   <soapServiceFunction></soapServiceFunction>
   <socketTimeout>-1</socketTimeout>
   <useServiceInfoFromWsdl>true</useServiceInfoFromWsdl>
   <variables>
      <defaultValue>GlobalVariable.Version</defaultValue>
      <description></description>
      <id>81071f14-6f7c-49c8-8daa-e298f28dc765</id>
      <masked>false</masked>
      <name>Version</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.$guid</defaultValue>
      <description></description>
      <id>432ca2dc-06d0-40d5-9da3-a983bf18b597</id>
      <masked>false</masked>
      <name>$guid</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.Identity-Key</defaultValue>
      <description></description>
      <id>174be581-72c0-4b6b-9598-e599ff5729da</id>
      <masked>false</masked>
      <name>Identity-Key</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.XAUTH_TRAVELPORT_ACCESSGROUP_1G</defaultValue>
      <description></description>
      <id>e33f8641-6a8d-456d-bfa9-389e6971671c</id>
      <masked>false</masked>
      <name>XAUTH_TRAVELPORT_ACCESSGROUP_1G</name>
   </variables>
   <wsdlAddress></wsdlAddress>
</WebServiceRequestEntity>
