<?xml version="1.0" encoding="UTF-8"?>
<WebServiceRequestEntity>
   <description></description>
   <name>Add Payment Instruction Post Commit Reservation</name>
   <tag></tag>
   <elementGuidId>893684c5-4e40-461a-a797-78c80f518a37</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <connectionTimeout>-1</connectionTimeout>
   <followRedirects>false</followRedirects>
   <httpBody></httpBody>
   <httpBodyContent>{
  &quot;text&quot;: &quot;{\n  \&quot;Payment\&quot;: {\n    \&quot;id\&quot;: \&quot;payment_1\&quot;,\n    \&quot;Identifier\&quot;: {\n      \&quot;authority\&quot;: \&quot;Travelport\&quot;,\n      \&quot;value\&quot;: \&quot;A0656EFF-FAF4-456F-B061-0161008D6A5E\&quot;\n    },\n    \&quot;Amount\&quot;: {\n      \&quot;code\&quot;: \&quot;${currencyCode}\&quot;,\n      \&quot;minorUnit\&quot;: 2,\n      \&quot;currencySource\&quot;: \&quot;Charged\&quot;,\n      \&quot;approximateInd\&quot;: true,\n      \&quot;value\&quot;: ${TotalAmount}\n    },\n    \&quot;FormOfPaymentIdentifier\&quot;: {\n      \&quot;id\&quot;: \&quot;formOfPayment_1\&quot;,\n      \&quot;FormOfPaymentRef\&quot;: \&quot;formOfPayment_1\&quot;,\n      \&quot;Identifier\&quot;: {\n        \&quot;authority\&quot;: \&quot;Travelport\&quot;,\n        \&quot;value\&quot;: \&quot;A0656EFF-FAF4-456F-B061-0161008D6FOP\&quot;\n      }\n    },\n    \&quot;OfferIdentifier\&quot;: [\n      {\n        \&quot;id\&quot;: \&quot;offer_1\&quot;,\n        \&quot;offerRef\&quot;: \&quot;offer_1\&quot;,\n        \&quot;Identifier\&quot;: {\n          \&quot;authority\&quot;: \&quot;Travelport\&quot;,\n          \&quot;value\&quot;: \&quot;${offerIdentifierPostCommitt}\&quot;\n        }\n      }\n    ]\n  }\n}&quot;,
  &quot;contentType&quot;: &quot;application/json&quot;,
  &quot;charset&quot;: &quot;UTF-8&quot;
}</httpBodyContent>
   <httpBodyType>text</httpBodyType>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>E2ETrackingID</name>
      <type>Main</type>
      <value>${guid}</value>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Content-Type</name>
      <type>Main</type>
      <value>application/json</value>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>XAUTH_TRAVELPORT_ACCESSGROUP</name>
      <type>Main</type>
      <value>${XAUTH_TRAVELPORT_ACCESSGROUP_1G}</value>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Accept</name>
      <type>Main</type>
      <value>application/json</value>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Content-Version</name>
      <type>Main</type>
      <value>${Version}</value>
   </httpHeaderProperties>
   <katalonVersion>8.1.0</katalonVersion>
   <maxResponseSize>-1</maxResponseSize>
   <migratedVersion>5.4.1</migratedVersion>
   <restRequestMethod>POST</restRequestMethod>
   <restUrl>https://api.apim-a.zu2.qa.travelport.io:443/uat/${Version}/air/paymentoffer/reservationworkbench/${eCacheId}/payments</restUrl>
   <serviceType>RESTful</serviceType>
   <soapBody></soapBody>
   <soapHeader></soapHeader>
   <soapRequestMethod></soapRequestMethod>
   <soapServiceEndpoint></soapServiceEndpoint>
   <soapServiceFunction></soapServiceFunction>
   <socketTimeout>-1</socketTimeout>
   <useServiceInfoFromWsdl>true</useServiceInfoFromWsdl>
   <variables>
      <defaultValue>GlobalVariable.Version</defaultValue>
      <description></description>
      <id>c1adb0f8-b976-4fea-a113-5a2c39548765</id>
      <masked>false</masked>
      <name>Version</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.eCacheId</defaultValue>
      <description></description>
      <id>928842d6-41c4-4092-a3eb-1ca596127149</id>
      <masked>false</masked>
      <name>eCacheId</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.guid</defaultValue>
      <description></description>
      <id>94fb3782-8df4-40dc-bf3a-d1ae67235604</id>
      <masked>false</masked>
      <name>guid</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.XAUTH_TRAVELPORT_ACCESSGROUP_1G</defaultValue>
      <description></description>
      <id>7529d9cf-697c-483e-a713-9b6684a3daec</id>
      <masked>false</masked>
      <name>XAUTH_TRAVELPORT_ACCESSGROUP_1G</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.currencyCode</defaultValue>
      <description></description>
      <id>519813e3-b45f-442b-8a71-483b6c9cff51</id>
      <masked>false</masked>
      <name>currencyCode</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.TotalAmount</defaultValue>
      <description></description>
      <id>6dbbfb01-13eb-47dc-941a-d66920482fa0</id>
      <masked>false</masked>
      <name>TotalAmount</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.offerIdentifierPostCommitt</defaultValue>
      <description></description>
      <id>64c2c83d-af46-4a3f-8b6a-be3d8ad3070e</id>
      <masked>false</masked>
      <name>offerIdentifierPostCommitt</name>
   </variables>
   <wsdlAddress></wsdlAddress>
</WebServiceRequestEntity>
