<?xml version="1.0" encoding="UTF-8"?>
<WebServiceRequestEntity>
   <description></description>
   <name>Add Payment Post Commit Reservation - Credit</name>
   <tag></tag>
   <elementGuidId>819f0c75-b2fb-4833-ae88-9c2a07018076</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <connectionTimeout>-1</connectionTimeout>
   <followRedirects>false</followRedirects>
   <httpBody></httpBody>
   <httpBodyContent>{
  &quot;text&quot;: &quot;{\r\n  \&quot;Payment\&quot;: {\r\n    \&quot;id\&quot;: \&quot;paymentCard_4\&quot;,\r\n    \&quot;Identifier\&quot;: {\r\n      \&quot;authority\&quot;: \&quot;Travelport\&quot;,\r\n      \&quot;value\&quot;: \&quot;A0656EFF-FAF4-456F-B061-0161008D6A6E\&quot;\r\n    },\r\n    \&quot;Amount\&quot;: {\r\n      \&quot;code\&quot;: \&quot;${currencyCode_held}\&quot;,  \r\n      \&quot;minorUnit\&quot;: 2, \r\n      \&quot;currencySource\&quot;: \&quot;Charged\&quot;, \r\n      \&quot;approximateInd\&quot;: true, \r\n      \&quot;value\&quot;: \&quot;${total_price_amount_held}\&quot;\r\n    },\r\n    \&quot;FormOfPaymentIdentifier\&quot;: {\r\n      \&quot;id\&quot;: \&quot;formOfPayment_5\&quot;,\r\n      \&quot;FormOfPaymentRef\&quot;: \&quot;formOfPayment_5\&quot;,\r\n      \&quot;Identifier\&quot;: {\r\n          \&quot;authority\&quot;: \&quot;Travelport\&quot;,\r\n          \&quot;value\&quot;: \&quot;A0656EFF-FAF4-456F-B061-0161008D6FOP\&quot;\r\n      }\r\n      \r\n    },\r\n    \&quot;OfferIdentifier\&quot;: [\r\n      {\r\n        \&quot;id\&quot;: \&quot;Offer_1\&quot;,\r\n        \&quot;offerRef\&quot;: \&quot;Offer_1\&quot;,\r\n        \&quot;Identifier\&quot;: {\r\n          \&quot;authority\&quot;: \&quot;${price_authority_held}\&quot;,\r\n          \&quot;value\&quot;: \&quot;${price_identfier_value_held}\&quot;\r\n        }\r\n      }\r\n    ]\r\n  }\r\n}&quot;,
  &quot;contentType&quot;: &quot;application/json&quot;,
  &quot;charset&quot;: &quot;UTF-8&quot;
}</httpBodyContent>
   <httpBodyType>text</httpBodyType>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>trackingId</name>
      <type>Main</type>
      <value>${guid}</value>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Authorization</name>
      <type>Main</type>
      <value>${token}</value>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Content-Type</name>
      <type>Main</type>
      <value>application/json</value>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>XAUTH_TRAVELPORT_ACCESSGROUP</name>
      <type>Main</type>
      <value>${XAUTH_TRAVELPORT_ACCESSGROUP_1G_XB7}</value>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Accept</name>
      <type>Main</type>
      <value>application/json</value>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Content-Version</name>
      <type>Main</type>
      <value>${version}</value>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Accept-Version</name>
      <type>Main</type>
      <value>6</value>
   </httpHeaderProperties>
   <katalonVersion>8.0.5</katalonVersion>
   <maxResponseSize>-1</maxResponseSize>
   <migratedVersion>5.4.1</migratedVersion>
   <restRequestMethod>POST</restRequestMethod>
   <restUrl>${ts_environment}/${version}/air/paymentoffer/reservationworkbench/${eCacheIdUa}/payments</restUrl>
   <serviceType>RESTful</serviceType>
   <soapBody></soapBody>
   <soapHeader></soapHeader>
   <soapRequestMethod></soapRequestMethod>
   <soapServiceEndpoint></soapServiceEndpoint>
   <soapServiceFunction></soapServiceFunction>
   <socketTimeout>-1</socketTimeout>
   <useServiceInfoFromWsdl>true</useServiceInfoFromWsdl>
   <variables>
      <defaultValue>GlobalVariable.ts_environment</defaultValue>
      <description></description>
      <id>a4d3f202-0c2a-4f30-b3b6-9520655272a2</id>
      <masked>false</masked>
      <name>ts_environment</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.version</defaultValue>
      <description></description>
      <id>c5dd32bb-ed48-47c5-84d8-1a0dc672172b</id>
      <masked>false</masked>
      <name>version</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.eCacheIdUa</defaultValue>
      <description></description>
      <id>926160f6-c9fd-4119-a8af-127b2913ae12</id>
      <masked>false</masked>
      <name>eCacheIdUa</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.guid</defaultValue>
      <description></description>
      <id>9324e26a-9d8d-4812-8b18-718e6368e50f</id>
      <masked>false</masked>
      <name>guid</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.token</defaultValue>
      <description></description>
      <id>dfd89d47-3786-4ac1-96eb-5cacc205ca8f</id>
      <masked>false</masked>
      <name>token</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.XAUTH_TRAVELPORT_ACCESSGROUP_1G_XB7</defaultValue>
      <description></description>
      <id>e2695177-9426-4cfd-8253-6387b16dadf8</id>
      <masked>false</masked>
      <name>XAUTH_TRAVELPORT_ACCESSGROUP_1G_XB7</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.currencyCode_held</defaultValue>
      <description></description>
      <id>9626cd8b-add9-41e1-841e-b6c57db58ac0</id>
      <masked>false</masked>
      <name>currencyCode_held</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.total_price_amount_held</defaultValue>
      <description></description>
      <id>01f27a27-0ce2-4419-9024-ef9e76b78fcf</id>
      <masked>false</masked>
      <name>total_price_amount_held</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.price_authority_held</defaultValue>
      <description></description>
      <id>c3f3ed13-f94c-4ae6-8b92-e5407e695f28</id>
      <masked>false</masked>
      <name>price_authority_held</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.price_identfier_value_held</defaultValue>
      <description></description>
      <id>ed25c963-cfc7-439a-93b2-2528b4f03990</id>
      <masked>false</masked>
      <name>price_identfier_value_held</name>
   </variables>
   <wsdlAddress></wsdlAddress>
</WebServiceRequestEntity>
