<?xml version="1.0" encoding="UTF-8"?>
<WebServiceRequestEntity>
   <description></description>
   <name>Search Request One Way NDC - UA</name>
   <tag></tag>
   <elementGuidId>4f9db27d-78f1-49e4-943e-bcf2a128d533</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <connectionTimeout>-1</connectionTimeout>
   <followRedirects>false</followRedirects>
   <httpBody></httpBody>
   <httpBodyContent>{
  &quot;text&quot;: &quot;{  \r\n   \&quot;CatalogOfferingsQueryRequest\&quot;:{  \r\n      \&quot;CatalogOfferingsRequest\&quot;:[  \r\n         {  \r\n            \&quot;@type\&quot;:\&quot;CatalogOfferingsRequestAir\&quot;,\r\n            \&quot;maxNumberOfOffersToReturn\&quot;:50,\r\n            \&quot;contentSourceList\&quot;:[\&quot;NDC\&quot;],\r\n            \&quot;offersPerPage\&quot;:100,\r\n            \&quot;returnBrandedFaresInd\&quot;:false,\r\n            \&quot;PassengerCriteria\&quot;:[  \r\n               {  \r\n                  \&quot;number\&quot;:1,\r\n                  \&quot;age\&quot;:25,\r\n                  \&quot;passengerTypeCode\&quot;:\&quot;ADT\&quot;\r\n               }\r\n            ],\r\n            \&quot;SearchCriteriaFlight\&quot;:[  \r\n               {  \r\n                  \&quot;@type\&quot;:\&quot;SearchCriteriaFlight\&quot;,\r\n                  \&quot;departureDate\&quot;:\&quot;2021-07-10\&quot;,\r\n                  \&quot;From\&quot;:{  \r\n                     \&quot;value\&quot;:\&quot;NRT\&quot;\r\n                  },\r\n                  \&quot;To\&quot;:{  \r\n                     \&quot;value\&quot;:\&quot;LAX\&quot;\r\n                  }\r\n               }\r\n            ],\r\n            \&quot;SearchModifiersAir\&quot;:{  \r\n               \&quot;CarrierPreference\&quot;:[  \r\n                  {  \r\n                     \&quot;type\&quot;:\&quot;Permitted\&quot;,\r\n                     \&quot;carriers\&quot;:[\&quot;UA\&quot;]\r\n                  }\r\n               ]\r\n            }\r\n         }\r\n      ]\r\n   }\r\n}&quot;,
  &quot;contentType&quot;: &quot;application/json&quot;,
  &quot;charset&quot;: &quot;UTF-8&quot;
}</httpBodyContent>
   <httpBodyType>text</httpBodyType>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Accept</name>
      <type>Main</type>
      <value>application/json</value>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Content-Type</name>
      <type>Main</type>
      <value>application/json</value>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Authorization</name>
      <type>Main</type>
      <value>${token}</value>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>E2ETrackingID</name>
      <type>Main</type>
      <value>${guid}</value>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>XAUTH_TRAVELPORT_ACCESSGROUP</name>
      <type>Main</type>
      <value>${XAUTH_TRAVELPORT_ACCESSGROUP_1G_XB7}</value>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Accept-Version</name>
      <type>Main</type>
      <value>${version}</value>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Content-Version</name>
      <type>Main</type>
      <value>${version}</value>
   </httpHeaderProperties>
   <katalonVersion>8.0.5</katalonVersion>
   <maxResponseSize>-1</maxResponseSize>
   <migratedVersion>5.4.1</migratedVersion>
   <restRequestMethod>POST</restRequestMethod>
   <restUrl>${ts_environment}/${version}/air/search/catalogofferings?view=detail</restUrl>
   <serviceType>RESTful</serviceType>
   <soapBody></soapBody>
   <soapHeader></soapHeader>
   <soapRequestMethod></soapRequestMethod>
   <soapServiceEndpoint></soapServiceEndpoint>
   <soapServiceFunction></soapServiceFunction>
   <socketTimeout>-1</socketTimeout>
   <useServiceInfoFromWsdl>true</useServiceInfoFromWsdl>
   <variables>
      <defaultValue>GlobalVariable.ts_environment</defaultValue>
      <description></description>
      <id>3f857a99-1d12-42a6-8a4a-f730df98cdca</id>
      <masked>false</masked>
      <name>ts_environment</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.version</defaultValue>
      <description></description>
      <id>1d7604e5-9868-47ca-b5bc-0e8bfa959985</id>
      <masked>false</masked>
      <name>version</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.token</defaultValue>
      <description></description>
      <id>629dd2c8-f22a-45a6-ad78-9b36db9d5c3f</id>
      <masked>false</masked>
      <name>token</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.guid</defaultValue>
      <description></description>
      <id>bc1d2d28-fdfc-4679-80f3-4aaf6338faf2</id>
      <masked>false</masked>
      <name>guid</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.XAUTH_TRAVELPORT_ACCESSGROUP_1G_XB7</defaultValue>
      <description></description>
      <id>b76fec36-4975-43fe-8b90-b4bdaba6a6d9</id>
      <masked>false</masked>
      <name>XAUTH_TRAVELPORT_ACCESSGROUP_1G_XB7</name>
   </variables>
   <wsdlAddress></wsdlAddress>
</WebServiceRequestEntity>
