<?xml version="1.0" encoding="UTF-8"?>
<WebServiceRequestEntity>
   <description></description>
   <name>Search Request One Way NDC - AA</name>
   <tag></tag>
   <elementGuidId>bb57e4eb-9319-42e6-99aa-a7e11ed7ead4</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <connectionTimeout>-1</connectionTimeout>
   <followRedirects>false</followRedirects>
   <httpBody></httpBody>
   <httpBodyContent>{
  &quot;text&quot;: &quot;{  \r\n   \&quot;CatalogOfferingsQueryRequest\&quot;:{  \r\n      \&quot;CatalogOfferingsRequest\&quot;:[  \r\n         {  \r\n            \&quot;@type\&quot;:\&quot;CatalogOfferingsRequestAir\&quot;,\r\n            \&quot;maxNumberOfOffersToReturn\&quot;:50,\r\n            \&quot;contentSourceList\&quot;:[\&quot;NDC\&quot;],\r\n            \&quot;offersPerPage\&quot;:50,\r\n            \&quot;returnBrandedFaresInd\&quot;:false,\r\n            \&quot;PassengerCriteria\&quot;:[  \r\n               {  \r\n                  \&quot;number\&quot;:1,\r\n                  \&quot;age\&quot;:25,\r\n                  \&quot;passengerTypeCode\&quot;:\&quot;ADT\&quot;\r\n               },\r\n               {  \r\n                  \&quot;number\&quot;:1,\r\n                  \&quot;age\&quot;:12,\r\n                  \&quot;passengerTypeCode\&quot;:\&quot;CHD\&quot;\r\n               }\r\n            ],\r\n            \&quot;SearchCriteriaFlight\&quot;:[  \r\n               {  \r\n                  \&quot;@type\&quot;:\&quot;SearchCriteriaFlight\&quot;,\r\n                  \&quot;departureDate\&quot;:\&quot;${InitialDeparture}\&quot;,\r\n                  \&quot;From\&quot;:{  \r\n                     \&quot;value\&quot;:\&quot;ATL\&quot;\r\n                  },\r\n                  \&quot;To\&quot;:{  \r\n                     \&quot;value\&quot;:\&quot;LAX\&quot;\r\n                  }\r\n               }\r\n            ],\r\n            \&quot;SearchModifiersAir\&quot;:{  \r\n            \&quot;excludeGround\&quot;:\&quot;Train\&quot;,\r\n               \&quot;CarrierPreference\&quot;:[  \r\n                  {  \r\n                     \&quot;type\&quot;:\&quot;Permitted\&quot;,\r\n                     \&quot;carriers\&quot;:[\&quot;AA\&quot;]\r\n                  }\r\n               ]\r\n            }\r\n         }\r\n      ]\r\n   }\r\n}&quot;,
  &quot;contentType&quot;: &quot;application/json&quot;,
  &quot;charset&quot;: &quot;UTF-8&quot;
}</httpBodyContent>
   <httpBodyType>text</httpBodyType>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Accept</name>
      <type>Main</type>
      <value>application/json</value>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Content-Type</name>
      <type>Main</type>
      <value>application/json</value>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Authorization</name>
      <type>Main</type>
      <value>${token}</value>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>E2ETrackingID</name>
      <type>Main</type>
      <value>${guid}</value>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>XAUTH_TRAVELPORT_ACCESSGROUP</name>
      <type>Main</type>
      <value>${XAUTH_TRAVELPORT_ACCESSGROUP_1G_XB7}</value>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Accept-Version</name>
      <type>Main</type>
      <value>${version}</value>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Content-Version</name>
      <type>Main</type>
      <value>${version}</value>
   </httpHeaderProperties>
   <katalonVersion>8.0.5</katalonVersion>
   <maxResponseSize>-1</maxResponseSize>
   <migratedVersion>5.4.1</migratedVersion>
   <restRequestMethod>POST</restRequestMethod>
   <restUrl>${ts_environment}/${version}/air/search/catalogofferings?view=detail</restUrl>
   <serviceType>RESTful</serviceType>
   <soapBody></soapBody>
   <soapHeader></soapHeader>
   <soapRequestMethod></soapRequestMethod>
   <soapServiceEndpoint></soapServiceEndpoint>
   <soapServiceFunction></soapServiceFunction>
   <socketTimeout>-1</socketTimeout>
   <useServiceInfoFromWsdl>true</useServiceInfoFromWsdl>
   <variables>
      <defaultValue>GlobalVariable.ts_environment</defaultValue>
      <description></description>
      <id>596e56eb-b884-4030-ac10-93695b6c0eb0</id>
      <masked>false</masked>
      <name>ts_environment</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.version</defaultValue>
      <description></description>
      <id>a5b5075a-8432-415e-bbe7-ad5526fb704a</id>
      <masked>false</masked>
      <name>version</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.token</defaultValue>
      <description></description>
      <id>b910e263-e811-4c98-b310-06efa5d716e7</id>
      <masked>false</masked>
      <name>token</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.guid</defaultValue>
      <description></description>
      <id>89219d8b-6f9f-49d1-a3d9-4c3dd97ead9b</id>
      <masked>false</masked>
      <name>guid</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.XAUTH_TRAVELPORT_ACCESSGROUP_1G_XB7</defaultValue>
      <description></description>
      <id>c7e906f9-1b65-4735-a609-62071b53240c</id>
      <masked>false</masked>
      <name>XAUTH_TRAVELPORT_ACCESSGROUP_1G_XB7</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.InitialDeparture</defaultValue>
      <description></description>
      <id>3e9f0e66-d637-4818-aee1-2a62dc37cd46</id>
      <masked>false</masked>
      <name>InitialDeparture</name>
   </variables>
   <wsdlAddress></wsdlAddress>
</WebServiceRequestEntity>
