<?xml version="1.0" encoding="UTF-8"?>
<WebServiceRequestEntity>
   <description></description>
   <name>Search Request - AA LAX-ATL</name>
   <tag></tag>
   <elementGuidId>dd93aa53-af27-4b90-ab95-2cdf0a7cd2a7</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <connectionTimeout>-1</connectionTimeout>
   <followRedirects>false</followRedirects>
   <httpBody></httpBody>
   <httpBodyContent>{
  &quot;text&quot;: &quot;{\n\t\&quot;CatalogOfferingsQueryRequest\&quot;: {\n\t\t\&quot;CatalogOfferingsRequest\&quot;: [\n\t\t\t{\n\t\t\t\t\&quot;@type\&quot;: \&quot;CatalogOfferingsRequestAir\&quot;,\n\t\t\t\t\&quot;maxNumberOfOffersToReturn\&quot;: 50,\n\t\t\t\t\&quot;offersPerPage\&quot;: 20,\n\t\t\t\t\&quot;contentSourceList\&quot;: [\n\t\t\t\t\t\&quot;NDC\&quot;\n\t\t\t\t],\n\t\t\t\t\&quot;PassengerCriteria\&quot;: [\n\t\t\t\t\t{\n\t\t\t\t\t\t\&quot;number\&quot;: 1,\n\t\t\t\t\t\t\&quot;passengerTypeCode\&quot;: \&quot;ADT\&quot;\n\t\t\t\t\t},\n\t\t\t\t\t{\n\t\t\t\t\t\t\&quot;number\&quot;: 1,\n\t\t\t\t\t\t\&quot;passengerTypeCode\&quot;: \&quot;CHD\&quot;\n\t\t\t\t\t}\n\t\t\t\t],\n\t\t\t\t\&quot;SearchCriteriaFlight\&quot;: [\n\t\t\t\t\t{\n\t\t\t\t\t\t\&quot;departureDate\&quot;: \&quot;${InitialDeparture}\&quot;,\n\t\t\t\t\t\t\&quot;From\&quot;: {\n\t\t\t\t\t\t\t\&quot;value\&quot;: \&quot;LAX\&quot;\n\t\t\t\t\t\t},\n\t\t\t\t\t\t\&quot;To\&quot;: {\n\t\t\t\t\t\t\t\&quot;value\&quot;: \&quot;ATL\&quot;\n\t\t\t\t\t\t}\n\t\t\t\t\t}\n\t\t\t\t],\n\t\t\t\t\&quot;SearchModifiersAir\&quot;: {\n\t\t\t\t\t\&quot;CarrierPreference\&quot;: [\n\t\t\t\t\t\t{\n\t\t\t\t\t\t\t\&quot;type\&quot;: \&quot;Permitted\&quot;,\n\t\t\t\t\t\t\t\&quot;carriers\&quot;: [\n\t\t\t\t\t\t\t\t\&quot;AA\&quot;\n\t\t\t\t\t\t\t]\n\t\t\t\t\t\t}\n\t\t\t\t\t],\n\t\t\t\t\t\&quot;CabinPreference\&quot;: [\n\t\t\t\t\t\t{\n\t\t\t\t\t\t\t\&quot;type\&quot;: \&quot;Permitted\&quot;,\n\t\t\t\t\t\t\t\&quot;cabins\&quot;: [\n\t\t\t\t\t\t\t\t\&quot;Economy\&quot;\n\t\t\t\t\t\t\t]\n\t\t\t\t\t\t}\n\t\t\t\t\t]\n\t\t\t\t}\n\t\t\t}\n\t\t]\n\t}\n}&quot;,
  &quot;contentType&quot;: &quot;application/json&quot;,
  &quot;charset&quot;: &quot;UTF-8&quot;
}</httpBodyContent>
   <httpBodyType>text</httpBodyType>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Accept</name>
      <type>Main</type>
      <value>application/json</value>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Content-Type</name>
      <type>Main</type>
      <value>application/json</value>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Authorization</name>
      <type>Main</type>
      <value>${token}</value>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>E2ETrackingID</name>
      <type>Main</type>
      <value>${guid}</value>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>XAUTH_TRAVELPORT_ACCESSGROUP</name>
      <type>Main</type>
      <value>${XAUTH_TRAVELPORT_ACCESSGROUP_1G_XB7}</value>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Accept-Version</name>
      <type>Main</type>
      <value>${version}</value>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Content-Version</name>
      <type>Main</type>
      <value>${version}</value>
   </httpHeaderProperties>
   <katalonVersion>8.0.5</katalonVersion>
   <maxResponseSize>-1</maxResponseSize>
   <migratedVersion>5.4.1</migratedVersion>
   <restRequestMethod>POST</restRequestMethod>
   <restUrl>${ts_environment}/${version}/air/search/catalogofferings?view=detail</restUrl>
   <serviceType>RESTful</serviceType>
   <soapBody></soapBody>
   <soapHeader></soapHeader>
   <soapRequestMethod></soapRequestMethod>
   <soapServiceEndpoint></soapServiceEndpoint>
   <soapServiceFunction></soapServiceFunction>
   <socketTimeout>-1</socketTimeout>
   <useServiceInfoFromWsdl>true</useServiceInfoFromWsdl>
   <variables>
      <defaultValue>GlobalVariable.ts_environment</defaultValue>
      <description></description>
      <id>e10e26a9-af81-462d-b7b6-3e9cb06979fc</id>
      <masked>false</masked>
      <name>ts_environment</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.version</defaultValue>
      <description></description>
      <id>e957b3d4-6139-4e54-8aa2-bb2bf71d88ef</id>
      <masked>false</masked>
      <name>version</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.token</defaultValue>
      <description></description>
      <id>f86d9d39-1180-4dc7-86b2-7ab0a7f8bc1d</id>
      <masked>false</masked>
      <name>token</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.guid</defaultValue>
      <description></description>
      <id>d041a962-6329-435f-b04d-2403ec393d5d</id>
      <masked>false</masked>
      <name>guid</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.XAUTH_TRAVELPORT_ACCESSGROUP_1G_XB7</defaultValue>
      <description></description>
      <id>157632b1-9771-41a9-b894-2d0c9f44a511</id>
      <masked>false</masked>
      <name>XAUTH_TRAVELPORT_ACCESSGROUP_1G_XB7</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.InitialDeparture</defaultValue>
      <description></description>
      <id>beddac89-4913-4f96-9ecf-6e3ca121d63d</id>
      <masked>false</masked>
      <name>InitialDeparture</name>
   </variables>
   <wsdlAddress></wsdlAddress>
</WebServiceRequestEntity>
