<?xml version="1.0" encoding="UTF-8"?>
<WebServiceRequestEntity>
   <description></description>
   <name>Search Request One Way NDC - QF FFS v6</name>
   <tag></tag>
   <elementGuidId>d25f23a2-8ba3-4d8f-8532-5c6200cbbdc8</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <connectionTimeout>-1</connectionTimeout>
   <followRedirects>false</followRedirects>
   <httpBody></httpBody>
   <httpBodyContent>{
  &quot;text&quot;: &quot;{  \r\n   \&quot;CatalogProductOfferingsQueryRequest\&quot;:{  \r\n      \&quot;CatalogProductOfferingsRequest\&quot;:\r\n         {  \r\n            \&quot;@type\&quot;:\&quot;CatalogProductOfferingsRequestAir\&quot;,\r\n            \&quot;contentSourceList\&quot;:[\&quot;NDC\&quot;],\r\n            \&quot;returnBrandedFaresInd\&quot;:false,\r\n            \&quot;PassengerCriteria\&quot;:[  \r\n               {  \r\n                  \&quot;number\&quot;:1,\r\n                  \&quot;age\&quot;:25,\r\n                  \&quot;passengerTypeCode\&quot;:\&quot;ADT\&quot;\r\n               }\r\n            ],\r\n            \&quot;SearchCriteriaFlight\&quot;:[  \r\n               {  \r\n                  \&quot;@type\&quot;:\&quot;SearchCriteriaFlight\&quot;,\r\n                  \&quot;departureDate\&quot;:\&quot;${InitialDeparture}\&quot;,\r\n                  \&quot;From\&quot;:{  \r\n                     \&quot;value\&quot;:\&quot;SYD\&quot;\r\n                  },\r\n                  \&quot;To\&quot;:{  \r\n                     \&quot;value\&quot;:\&quot;MEL\&quot;\r\n                  }\r\n               }\r\n            ],\r\n            \&quot;SearchModifiersAir\&quot;:{  \r\n              \&quot;excludeGround\&quot;:\&quot;Train\&quot;,\r\n               \&quot;CarrierPreference\&quot;:[  \r\n                  {  \r\n                     \&quot;type\&quot;:\&quot;Permitted\&quot;,\r\n                     \&quot;carriers\&quot;:[\&quot;QF\&quot;]\r\n                  }\r\n               ]\r\n            }\r\n         }\r\n   }\r\n}&quot;,
  &quot;contentType&quot;: &quot;application/json&quot;,
  &quot;charset&quot;: &quot;UTF-8&quot;
}</httpBodyContent>
   <httpBodyType>text</httpBodyType>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Accept</name>
      <type>Main</type>
      <value>application/json</value>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Content-Type</name>
      <type>Main</type>
      <value>application/json</value>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Authorization</name>
      <type>Main</type>
      <value>${token}</value>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>E2ETrackingID</name>
      <type>Main</type>
      <value>${guid}</value>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>XAUTH_TRAVELPORT_ACCESSGROUP</name>
      <type>Main</type>
      <value>${XAUTH_TRAVELPORT_ACCESSGROUP_1G_682J}</value>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Accept-Version</name>
      <type>Main</type>
      <value>${version}</value>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Content-Version</name>
      <type>Main</type>
      <value>${version}</value>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>XAUTH_TRAVELPORT_TERMINAL_OVERRIDE</name>
      <type>Main</type>
      <value>C1FCF5</value>
   </httpHeaderProperties>
   <katalonVersion>8.0.5</katalonVersion>
   <maxResponseSize>-1</maxResponseSize>
   <migratedVersion>5.4.1</migratedVersion>
   <restRequestMethod>POST</restRequestMethod>
   <restUrl>${ts_environment}/${version}/air/farefamilysearch/catalogproductofferings</restUrl>
   <serviceType>RESTful</serviceType>
   <soapBody></soapBody>
   <soapHeader></soapHeader>
   <soapRequestMethod></soapRequestMethod>
   <soapServiceEndpoint></soapServiceEndpoint>
   <soapServiceFunction></soapServiceFunction>
   <socketTimeout>-1</socketTimeout>
   <useServiceInfoFromWsdl>true</useServiceInfoFromWsdl>
   <variables>
      <defaultValue>GlobalVariable.ts_environment</defaultValue>
      <description></description>
      <id>e9db0bb5-1ea4-4cde-bce3-14c409dafa99</id>
      <masked>false</masked>
      <name>ts_environment</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.version</defaultValue>
      <description></description>
      <id>17bfcb4a-8ad2-439a-9688-ae6983eca7e9</id>
      <masked>false</masked>
      <name>version</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.token</defaultValue>
      <description></description>
      <id>b68eb577-0fbb-4a71-8ba6-c6f2a5acca27</id>
      <masked>false</masked>
      <name>token</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.guid</defaultValue>
      <description></description>
      <id>c29195d3-fec1-4739-8432-f81f2037a3a6</id>
      <masked>false</masked>
      <name>guid</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.XAUTH_TRAVELPORT_ACCESSGROUP_1G_682J</defaultValue>
      <description></description>
      <id>b13a8c5e-e941-45f2-b4b2-0ceb86a7300d</id>
      <masked>false</masked>
      <name>XAUTH_TRAVELPORT_ACCESSGROUP_1G_682J</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.InitialDeparture</defaultValue>
      <description></description>
      <id>968cb334-efa2-46d2-aa3e-2ea6984f92d1</id>
      <masked>false</masked>
      <name>InitialDeparture</name>
   </variables>
   <wsdlAddress></wsdlAddress>
</WebServiceRequestEntity>
